// <auto-generated />
namespace SondaIT.CodeFirst.FluentAPI.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PisBackup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PisBackup));
        
        string IMigrationMetadata.Id
        {
            get { return "201507172335052_PisBackup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
