//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCoders.Integracao.Services.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LOGIN
    {
        public int ID_LOGIN { get; set; }
        public string NM_NOME { get; set; }
        public string DS_SENHA { get; set; }
    }
}
