//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCoders.SisAgendaTOP.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INCUBADORAEntities : DbContext
    {
        public INCUBADORAEntities()
            : base("name=INCUBADORAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TB_CONTATO> TB_CONTATO { get; set; }
        public DbSet<TB_SEXO> TB_SEXO { get; set; }
        public DbSet<TB_LOGIN> TB_LOGIN { get; set; }
    }
}
